base:
  project: StockPrediction
  random_state: 42
  target_col: close

data_source:
  raw_source: data/raw/
  precessed: data/processed/

load_data:
  path: data/processed/data.csv
  test_size: 0.2

model:
  path: models
  filename: model.pkl

reports:
  scores: report/scores.json

webapp_model_dir: models/model.pkl